version: '1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - API_VERSION=1.0.0
      - APP_NAME=time-based-key-value-store
      - DATABASE_DIALECT=postgresql
      - DATABASE_HOSTNAME=db
      - DATABASE_NAME=time-based-key-value-database
      - DATABASE_PASSWORD=test123
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    volumes:
      - /tmp:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=test123
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 2s
      retries: 20

